Пишем при деплое, если нет файлов

diff --git a/.github/workflows/secrets.yml b/.github/workflows/secrets.yml
--- a/.github/workflows/secrets.yml
+++ b/.github/workflows/secrets.yml
@@ -14,5 +14,9 @@ jobs:
 
       - name: secret "GEN_API_API_KEY" to ./ai/aiChat.js and ./laboratory/laboratory.js
         run: |
+          if [ ! -f "./ai/aiChat.js" ]; then
+              echo "Error: File doesn't exist."
+              exit 1
+          fi
           sed -i 's|__GEN_API_API_KEY__|${{ secrets.GEN_API_API_KEY }}|g' ./ai/aiChat.js
           sed -i 's|__GEN_API_API_KEY__|${{ secrets.GEN_API_API_KEY }}|g' ./laboratory/laboratory.js
